Update generate-psa.yaml

diff --git a/.github/workflows/generate-psa.yaml b/.github/workflows/generate-psa.yaml
--- a/.github/workflows/generate-psa.yaml
+++ b/.github/workflows/generate-psa.yaml
@@ -82,16 +82,16 @@ jobs:
 
       - name: Commit and push changes
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          PAT_TOKEN: ${{ secrets.POKEMON_PAT_TOKEN }}
         run: |
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git checkout main
-          git pull origin main --no-rebase || echo "Pull failed, proceeding to push"
+          git pull origin main --no-rebase || echo "Pull failed, continuing"
           git add .
           if ! git diff --cached --quiet; then
               git commit -m "Update PSA JSON for ${{ matrix.set }}"
-              git push origin main
+              git push https://${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
           else
               echo "No changes to commit"
 
